"""Criar tabela transacoes

Revision ID: f663715f5ec3
Revises: 36cf3a803917
Create Date: 2025-09-08 12:58:06.899425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f663715f5ec3'
down_revision: Union[str, Sequence[str], None] = '36cf3a803917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subcategorias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subcategorias_id'))

    op.drop_table('subcategorias')
    with op.batch_alter_table('transacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transacoes_id'))

    op.drop_table('transacoes')
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categorias_id'))

    op.drop_table('categorias')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('categoria_nome', sa.VARCHAR(), nullable=False),
    sa.Column('natureza', sa.VARCHAR(), nullable=False),
    sa.Column('limite', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('categoria_nome')
    )
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categorias_id'), ['id'], unique=False)

    op.create_table('transacoes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('valor', sa.FLOAT(), nullable=False),
    sa.Column('descricao', sa.VARCHAR(), nullable=False),
    sa.Column('parcela', sa.INTEGER(), nullable=True),
    sa.Column('total_parcelas', sa.INTEGER(), nullable=True),
    sa.Column('data_transacao', sa.DATETIME(), nullable=False),
    sa.Column('data_criacao', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('data_atualizacao', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('tipo', sa.VARCHAR(), nullable=False),
    sa.Column('natureza_transacao', sa.VARCHAR(), nullable=False),
    sa.Column('forma_pagamento', sa.VARCHAR(), nullable=False),
    sa.Column('categoria_id', sa.INTEGER(), nullable=False),
    sa.Column('subcategoria_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['subcategoria_id'], ['subcategorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transacoes_id'), ['id'], unique=False)

    op.create_table('subcategorias',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('subcategoria_nome', sa.VARCHAR(), nullable=False),
    sa.Column('categoria_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subcategorias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subcategorias_id'), ['id'], unique=False)

    # ### end Alembic commands ###
